apiVersion: apps/v1
kind: Deployment
metadata:
  name: dist_model-deployment
spec:
  replicas: 20 # Number of pods (containers) to run
  selector:
    matchLabels:
      app: dist_model-deployment
  template:
    metadata:
      labels:
        app: dist_model-deployment
    spec:
      containers:
      - name: dist_model-container # Name of the container within each pod
        imagePullPolicy: Always # Ensure latest version is pulled if available on registry or local cache is outdated.
        image: dist_model_alpine:0.1 # Use 'my-python-app' as an example; replace with actual registry URL if needed.
